Auction component
lcnem/botany pull request #136
Opened 2021-10-27 09:59 UTC by Senna46

未完成の暫定PRです。
auctionのパラメーター一覧ページとauction一覧をこのPRで実装する予定です。

- [x]  パラメーター一覧
- [x]  オークション一覧

@YasunoriMATSUOKA 
CDPと同様に `botany.auction.IParams`での実装を予定していたのですが、APIで得られる`InlineResponse2002Params`はパラメーターがすべて string で、入れることができなかったので、`InlineResponse2002Params`をそのまま用いていますが、これで問題ないでしょうか？

```
interface IParams {

            /** Params max_auction_duration */
            max_auction_duration?: (google.protobuf.IDuration|null);

            /** Params bid_duration */
            bid_duration?: (google.protobuf.IDuration|null);

            /** Params increment_surplus */
            increment_surplus?: (string|null);

            /** Params increment_debt */
            increment_debt?: (string|null);

            /** Params increment_collateral */
            increment_collateral?: (string|null);
        }
```

2021-10-30 01:04 UTC, KimuraYu45z commented on projects/telescope-extension/src/app/pages/auction/auctions/auctions.component.ts
> +import { InlineResponse200Auctions } from 'projects/botany-client/src/openapi';
そうではなくて
openapiでいうところの

type_url
value

2つのみを持ってる変な型があるでしょう？そいつにたいしてunpackCosmosAnyをかけないといけない

2021-11-02 06:50 UTC, Senna46 commented
@YasunoriMATSUOKA @KimuraYu45z 
レビューお願いします。

昨日のJPYXの修正でAuction個別APIの問題 #137 が解決したので、Auction個別ページも実装しています（現状、得られるデータすべてを表示）

Auction一覧ページのPagenationに問題があったのでそれも修正しています。

現状の問題点としては`rest.botany.auction`APIで得られるデータとInlineResponseで規定されているデータ構造が合わないことが原因で`UnpackCosmosAny`でエラーが発生しています。
回避策として、

- pagesから渡すデータをany型
- viewsで受け取るデータをAPI Responseと整合性のある`botany.auction.CollateralAuction`

で表示させています。UI上の問題はないのと、JPYX or botany clientの修正になると思うので本PRはここでマージしてもよろしいでしょうか？

この問題は別にIssue立てておきます。

![auctiondetail](https://user-images.githubusercontent.com/29295263/139798505-f617d041-6b15-41de-bfba-4cd432f495a8.PNG)

2021-11-02 06:53 UTC, KimuraYu45z commented
規定されているデータ構造
って
type_url:stringとvalue:string

ですよね？

あと、Lotが[Object Object]になってるのは治したいです

2021-11-02 06:58 UTC, YasunoriMATSUOKA commented
anyを使わざるを得ない現状は、

botany-clientで定義された関数の返り値はunpackCosmosAnyされるべき型だが、実際に流れてきている値の型はunpackCoswmosAny後の型になってしまっていて、ミスマッチが生じているように見え、protoから自動生成しているbotany-clientに何か意図しない状況が生まれているのでは？

という心配をしていて、このまま進むのは危ないと感じています。

JPYXについては、他のタスクよりも、この点の問題解決を優先的にすすめてほしいというのが松岡の所感ですが、このプルリクを現段階でマージするか否かの判断は木村さんにお任せします。

2021-11-02 07:00 UTC, KimuraYu45z commented
以下ください。

- unpackCosmosAnyに入れる値をconsole.logしたもの
- unpackCosmosAnyで出たエラーのconsole

2021-11-02 07:01 UTC, Senna46 commented
Lotは凡ミスでした、修正しました。

InlineResponse200Auctionsがtype_url:stringとvalue:stringでこれをunpackCosmosAnyするとCollateralAuctionになるはずです。VScode上のエラーはないのですが、実際には下記エラーが出ます。

`base_auction.end_time`は存在するはずなのでよく分かりません。

![err](https://user-images.githubusercontent.com/29295263/139800304-d2284d25-13f8-4e24-bf6c-f5d0197fd908.PNG)

2021-11-02 07:02 UTC, KimuraYu45z commented
同様にわかってないまま進むのは危険だと思います。
リスクと不確実性は違うというもので、どれだけ危険(リスク)かがわかっていてその危険を放置するのはいいのですが、どれだけ危険かわからない（不確実性）のは放置はよくない、というのがよく言われる原則的な

2021-11-02 07:02 UTC, KimuraYu45z commented
入れる前の値もください

2021-11-02 07:06 UTC, Senna46 commented
入れる前のデータはこれです。

![data](https://user-images.githubusercontent.com/29295263/139801068-e5b20545-ee38-4f7a-b648-4def89a241bc.PNG)

2021-11-02 07:08 UTC, KimuraYu45z commented
end_timeの代わりにmax_end_timeっていうフィールドがあるんが原因っぽいですね

2021-11-02 07:09 UTC, KimuraYu45z commented
https://github.com/lcnem/jpyx/blob/main/proto/auction/auction.proto#L28
protoの型定義みたところ、end_timeもmax_end_timeも両方あるのが正常っぽいですね

2021-11-02 07:11 UTC, Senna46 commented
end_timeもあるように見えるのですが、順番が違うということですか？

2021-11-02 07:13 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/pages/auction/auctions/auctions.component.ts
> +  auctions$?: Observable<any>;
any関連の問題は、AuctionComponent以外にも、ここのAuctionsComponentの問題も解決しておかねば危ないと思っています。一応メモしておきます。

2021-11-02 07:13 UTC, KimuraYu45z commented
>botany-clientで定義された関数の返り値はunpackCosmosAnyされるべき型だが、実際に流れてきている値の型はunpackCoswmosAny後の型(のようなもの？)になってしまっていて、矛盾が生じているように見え
これは違うようでした。


- botany-clientで定義された関数の返り値の型: type_urlとvalueだけあるおかしなデータ型になっているはずで、これはunpackCosmosAnyしないといけない型であることを示します
  - 実際にはtype_urlではなく@typeが入ってきます
  - 実際にはvalueではなく`...value`と、スプレッド演算子が適用されるような形で入ってきます
  - 型定義と実際の値（type_urlと@type）が違うのはgrpc_gatewayのバグですおそらく
- 実際に流れてきている値: @typeがあるので、これは明確にunpackCosmosAnyしないといけない型であることを示します
- unpackCosmosAnyのエラー原因:end_timeがないから。
-

2021-11-02 07:15 UTC, KimuraYu45z commented
あほんまやよくみたらend timeありますね。

2021-11-02 07:20 UTC, KimuraYu45z commented
あー－－－botany clientのproto,jsの1539行め　みたら原因分かりました今書きます

2021-11-02 07:22 UTC, KimuraYu45z commented
エラーに書いてある原因行は見ると良いです



ようはend_timeがないって怒られてるんじゃなくて、end_timeはオブジェクトじゃないとだめだっていう怒られ方してるんですね。
どういうオブジェクト化というとprotobuf.TimeStamp型じゃないといけなくて、今あるend_timeは文字列になってますね（GoではTime型をjsonにすると文字列になる）

2021-11-02 07:24 UTC, KimuraYu45z commented
解決法はいくつかあり、手っ取り早いのはunpack cosmos anyをする前にbase.end_timeとbase.max_end_timeは文字列からprotobuf.TimeStamp型に変えてやるよう変換処理入れることだと思います
その変換処理いれたあとでunpackCosmosAnyしてやれば解決する

2021-11-02 07:30 UTC, Senna46 commented
unpack cosmos anyする前だとvalue:stringなのでbase.end_timeとbase.max_end_timeにアクセスできない気がするのですが、どのように変換すれば良いでしょうか＞
as anyしてからではあんまり意味ないですよね？

2021-11-02 07:30 UTC, Senna46 commented on projects/telescope-extension/src/app/pages/auction/auctions/auctions.component.ts
> +  auctions$?: Observable<any>;
おっしゃるように同じデータ構造なので個別もリストも同じ問題です

2021-11-02 07:34 UTC, KimuraYu45z commented
value:stringってのは型の話で、実態はbase.end_timeが入っているので、

data as {base: {end_time: string, max_end_time:string}} みたいにしとけば安全です

↑これを引数として受け取って、
base.end_timeとbase.max_end_timeは文字列からprotobuf.TimeStamp型に変えてやるよう変換処理入れ、
unknownとして返す

こういう関数作ればOK

2021-11-04 06:47 UTC, Senna46 commented
Date.parse()でStringからprotobuf.TimeStamp型に変換するようですが、これだとnumber型になり結局`Object expected`のエラーになります。
なにか回避策はありますでしょうか？

2021-11-04 06:48 UTC, KimuraYu45z commented
numberとして何が入るのかを調べてください

ミリ秒？

2021-11-04 06:49 UTC, Senna46 commented
ミリ秒です

2021-11-04 06:53 UTC, KimuraYu45z commented
ならあとはprotobuf.TimeStamp.newするだけでは

2021-11-04 07:00 UTC, Senna46 commented
botany-clientからインポートしgoogle.protobuf.Timestampだと引数がnumberではなく、`properties?: google.protobuf.ITimestamp | undefined`なようです

2021-11-04 07:14 UTC, KimuraYu45z commented
ITimestampつくったらいいじゃないですか

2021-11-04 07:16 UTC, KimuraYu45z commented
https://stackoverflow.com/questions/54849843/how-can-i-test-google-protobuf-timestamp-in-javascript

2021-11-04 08:29 UTC, Senna46 commented
@KimuraYu45z @YasunoriMATSUOKA 
ご指摘の点修正し、unpackCosmosAnyしてから、botany.auction.CollateralAuctionで値を受け渡す方式で実装しました。

end_time、max_end_timeはundefinedが返ってくる場合は非表示、undefinedでなければDate型で表示としたので今は非表示になっています。

2021-11-04 10:41 UTC, YasunoriMATSUOKA requested changes
@Senna46 
気になった点をコメントしました。確認＆修正お願いします。

cc: @KimuraYu45z 
もし方針違和感あったら、フォロー頂けると助かります。

2021-11-04 10:41 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/views/auction/auctions/auction/auction.component.ts
> +  }
@Senna46
このconstructorは最初に一回しか実行されず、その際、auction?は親コンポーネントからObservableなデータが流れてくる前のundefinedになっており、実際にそのあと流れてくるauctionのデータの中身によらず、必ずendTime, maxEndTimeがundefinedになってしまう実装になっているように思います。

親コンポーネント側でDate型に変換したObservableなクラス変数を作って、auctionと同様にasyncパイプで、子コンポーネントに渡し、子コンポーネントでそのまま表示するような実装にしてはどうでしょうか？

cc: @KimuraYu45z
木村さん、もし上記実装方針違和感あれば、フォローもらえると助かります。
よろしくお願いします。

2021-11-04 10:41 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/views/auction/auctions/auctions.component.html
> +            </span>
@Senna46 
この二つだけだと、auctionの一覧として少し情報少ないかなと感じました。
以下のフィールドの中で、has_received_bids(入札済か否か？)、corresponding_debt、max_bidあたりは、一覧に情報があることが望ましいと感じました。

cc: @KimuraYu45z 
どれくらいの情報を一覧表に表示するかの匙加減、上記指針問題ないか、確認させてください。

```json
{
      "@type": "/botany.auction.CollateralAuction",
      "base_auction": {
        "id": "1",
        "initiator": "liquidator",
        "lot": {
          "denom": "ubtc",
          "amount": "100"
        },
        "bidder": "",
        "bid": {
          "denom": "jpyx",
          "amount": "0"
        },
        "has_received_bids": false,
        "end_time": "9000-01-01T00:00:00Z",
        "max_end_time": "9000-01-01T00:00:00Z"
      },
      "corresponding_debt": {
        "denom": "debt",
        "amount": "472"
      },
      "max_bid": {
        "denom": "jpyx",
        "amount": "507"
      },
      "lot_returns": [
        {
          "address": "jpyx16eys6a8rd26vqx7275dafdpavwqejve2h3ah76",
          "weight": "100"
        }
      ]
    }
```

2021-11-04 12:54 UTC, Senna46 commented
@KimuraYu45z @YasunoriMATSUOKA 
指摘いただいた3点修正完了しました。

Auction一覧には煩雑になりそうだったので、ID、BTCの量、Bidderの有無（いる場合はBidder名）をChipで表示、Max Bidの4つの表示としました。

Auction個別ページのend timeも設定なしの値であり、前のコメントの画像と同じ時間で問題ないと思っています。

![auctions](https://user-images.githubusercontent.com/29295263/140316526-a048b591-3283-469d-8d45-61108dd49e97.PNG)
![auction](https://user-images.githubusercontent.com/29295263/140316533-6cf35f11-02f9-4ea2-b4ce-b3c91cb02a89.PNG)

2021-11-05 02:10 UTC, YasunoriMATSUOKA requested changes
@Senna46 
一覧画面、詳細画面の全体的な実装はLGTMだと思いましたが、
endTime, maxEndTimeの値が、あまりにも遠い将来の日付となっているように見え、問題がありそうです。
詳細はコードにコメント入れておいたので、確認の上、必要な修正をお願いします。

2021-11-05 02:10 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/pages/auction/auctions/auction/auction.component.ts
> +    );
@Senna46 
endTime, maxEndTimeいずれも、とても遠い将来の日付になっているように画面に表示される日付の情報からは見えていて、もし本当にこの条件でauctionが生成されているとしたら、いつになってもauctionでの落札イベント的なものが発生せず、auctionがいつまでたっても終わらない状況になってしまうように思います。

可能性としては、大まかには以下のいずれかの可能性が考えられると思うので、まずはフロントのAngular側でparseしている箇所の処理を中心に詳細にconsole.log等で確認の上、実際にどのような日付の情報がバックエンド側から流れてきているか詳細にデバッグしてもらえますか？

1. バックエンド側では正常なendTime, maxEndTimeのauctionが作成されているが、フロントエンド側でparseしたり変換したりした際にその方法に誤りがあり、異なる日付に変換されてしまっている
2. バックエンド側でそもそも誤ったendTime, maxEndTimeのauctionが作成されている

1の場合はAngular側を修正すればOKだと思いますが、2の場合はjpyxレポジトリ側の実装の修正が必要かもしれません。まずは、1, 2のどちらに問題があるか切り分けることを意識して、詳細にデバッグトライしてみてください。

cc: @KimuraYu45z 
状況によっては、サポート頂けると助かります。
お手数ですがよろしくお願いしますm(__)m

![image](https://user-images.githubusercontent.com/55148923/140446044-f99d5114-b4b4-41c9-9bdb-f68ad46862a7.png)

2021-11-05 02:16 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/pages/auction/auctions/auction/auction.component.ts
> +    );
@Senna46 
ノード上でauctionの一覧を取得するcliコマンド実行してみた結果、以下のようになったので、もしかするとjpyxレポジトリ側の実装に問題があるかもしれません。いずれにせよ、endTime, maxEndTime周り、詳細にデバッグしてみてください

```sh
~/jpyx-telescope# jpyxd query auction list-auction
auctions:
- '@type': /botany.auction.CollateralAuction
  base_auction:
    bid:
      amount: "0"
      denom: jpyx
    bidder: ""
    end_time: "9000-01-01T00:00:00Z"
    has_received_bids: false
    id: "1"
    initiator: liquidator
    lot:
      amount: "100"
      denom: ubtc
    max_end_time: "9000-01-01T00:00:00Z"
  corresponding_debt:
    amount: "472"
    denom: debt
  lot_returns:
  - address: jpyx16eys6a8rd26vqx7275dafdpavwqejve2h3ah76
    weight: "100"
  max_bid:
    amount: "507"
    denom: jpyx
- '@type': /botany.auction.CollateralAuction
  base_auction:
    bid:
      amount: "0"
      denom: jpyx
    bidder: ""
    end_time: "9000-01-01T00:00:00Z"
    has_received_bids: false
    id: "2"
    initiator: liquidator
    lot:
      amount: "100"
      denom: ubtc
    max_end_time: "9000-01-01T00:00:00Z"
  corresponding_debt:
    amount: "470"
    denom: debt
  lot_returns:
  - address: jpyx19pq852m26e8dclcmekj4d8us65evekxthpjnnk
    weight: "100"
  max_bid:
    amount: "505"
    denom: jpyx
pagination:
  next_key: null
  total: "2"
```

@KimuraYu45z 
もし、上記違和感あったら、フォローください。

2021-11-05 02:18 UTC, KimuraYu45z commented on projects/telescope-extension/src/app/pages/auction/auctions/auction/auction.component.ts
> +    );
これはバックエンド側に問題ありですね。確認します

2021-11-05 03:52 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/pages/auction/auctions/auction/auction.component.ts
> +    );
@KimuraYu45z cc: @Senna46 
バックエンド側に問題ありということであれば、このプルリクは、以下の変更提案だけ先に確認してもらって、その確認と対応が終わったら、いったん、このままマージしてもOKでしょうか？
https://github.com/lcnem/botany/pull/140
念のため確認させてください。

2021-11-05 03:57 UTC, KimuraYu45z commented on projects/telescope-extension/src/app/pages/auction/auctions/auction/auction.component.ts
> +    );
はい、フロントとしてはこれマージでいいと思います。

2021-11-05 04:09 UTC, YasunoriMATSUOKA approved these changes
@Senna46 cc: @KimuraYu45z 
以下問題は、バックエンド側に問題がありそうなので、これでこのプルリクはLGTMです。
https://github.com/lcnem/botany/pull/136#discussion_r743343109

ただ、変数名の名付け方等について、こうしておいたほうが良いのでは？というプルリク( https://github.com/lcnem/botany/pull/140 )を作成しておいたので、マージ前に内容確認して頂いて、問題無ければ、そのプルリクをマージした上で、このプルリクをマージしてください。

2021-11-05 08:18 UTC, Senna46 commented
変数名のPRをマージ、secoonds, nanosで表示には影響がなかったが、修正漏れてた場所を修正
これで本ブランチもマージします。

2021-11-05 08:49 UTC, merged