Auction Place Bid
lcnem/botany pull request #143
Opened 2021-11-11 07:44 UTC by Senna46

Auction Place Bidの実装です。

botany.auction.MsgPlaceBidには以下の3argが必要だったので、ActivatedRouteでauction_idを、bidderを得るためにbidコンポーネントにはKey-select guardをつけています。
amount, denomはフォームでの入力です。

Keyを持った状態でのデバッグ方法がわからず、動作確認はデプロイ後になると思ったのでPR作成しています。

@YasunoriMATSUOKA CC: @KimuraYu45z 
レビューお願いします。

```
            auction_id?: (Long|null);

            /** MsgPlaceBid bidder */
            bidder?: (string|null);

            /** MsgPlaceBid amount */
            amount?: (cosmos.base.v1beta1.ICoin|null);
```

![butoon](https://user-images.githubusercontent.com/29295263/141257351-440de52a-5da0-445a-8c95-2e1773a8703e.PNG)
![placebid](https://user-images.githubusercontent.com/29295263/141257357-35889930-31b3-4c6e-b769-feb44878f7fe.PNG)

2021-11-11 07:51 UTC, YasunoriMATSUOKA commented
botanyレポジトリのtelescopeの実装で、keyの情報が必要なデバッグを行う場合の流れ

1. telescopeレポジトリ側のkey createをlocalhost:4200で実行しておく
2. 1の後なら、botanyレポジトリ側のデバッグをlocalhost:4200/jpyxで行う場合、1でIndexedDBに登録したkeyの情報を同じドメイン扱いで使用可能

2021-11-11 08:06 UTC, Senna46 commented
@YasunoriMATSUOKA 

デバッグ方法ありがとうございます。
MsgPlaceBidは問題なく作れたようで、Service側も問題なく動いたのですが、Txが実際は生成されていない可能性があります。

TX hash: 783EBE19F0E00F74AF7BA02962EACF1F228C41EF1C7D7129C81EB5AEC34E0C6C
![bid](https://user-images.githubusercontent.com/29295263/141260439-c79ec1e4-656f-4f22-a433-1c02f10f7523.png)

http://a.test.jpyx.lcnem.net/のTelescopeでみたところ該当のTx hashの情報なし

何度か試しましたが、Auction情報にもTxにも反映されないのでバックエンドの問題かもしれません。少し原因究明してみます。

2021-11-11 08:08 UTC, YasunoriMATSUOKA commented
@Senna46 
まずはトランザクションをアナウンスした際のレスポンスを確認しましょう。
console.log等書いて、どんなログが返ってきているか確認してみてください。

2021-11-12 05:18 UTC, Senna46 commented
VPS上ではTx作成問題なし
nsgPlaceBidも問題なさそうなので原因わからず

```
root@jpyx-test-a:~# jpyxd tx auction place-bid 2 20jpyx --from main --chain-id jpyx-3-test
{"body":{"messages":[{"@type":"/botany.auction.MsgPlaceBid","auction_id":"2","bidder":"jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt","amount":{"denom":"jpyx","amount":"20"}}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
{"height":"403079","txhash":"310E2D0D9E463B4FB73E6038C4657F242E4ADF6CB3AE9C54BFF863B9EA74E5E6","codespace":"sdk","code":5,"data":"","raw_log":"failed to execute message; message index: 0: 1jpyx is smaller than 20jpyx: insufficient funds","logs":[],"info":"","gas_wanted":"200000","gas_used":"48468","tx":null,"timestamp":""}
```

2021-11-12 06:02 UTC, Senna46 commented
denom amount逆にしていただけでした、、
UIも少しオークション情報を表示するように若干変えましたが、Bidも正常にできています。

@YasunoriMATSUOKA CC: @KimuraYu45z 
レビューお願いします。

![bid](https://user-images.githubusercontent.com/29295263/141418001-1fdf6db9-3418-4cfa-b750-4899a2b10776.png)
![tx](https://user-images.githubusercontent.com/29295263/141418009-fc758bc4-e2aa-4600-b27a-f59b4b9caaaa.PNG)

2021-11-12 09:47 UTC, YasunoriMATSUOKA commented
@Senna46 
まだ詳細をレビューしていませんが、以下が気になりました。

上記リンクの件、現状に以下のような不安を感じています。以下リンクコメントの通りトランザクションが通っていたとしたら、100ubtcが担保としてロックされて作成された469jpyxのcdpに対して発生したauctionで、bidが1でトランザクションを通せたということになり、なんだか価格破壊過ぎるような気がしています。

実際には、多数の入札が想定され、現実から乖離しすぎたbidが入っていることを他の入札者が察知したら、他の入札者がもっと現実的なbidでの入札を入れるという競争が起こり、結果的に現実的なbidを提示した入札者が落札できる状況に収束するんだろうなとは思うものの、複数名からのauctionに対し、最も高額なbidを提示した入札者がきちんと落札できているか、デバッグしておいたほうが良いと感じているのですが、いかがですか？

閾値として最低価格みたいなのがあるのが自然だと思うけどないの？ということも思ったりもしました。auctionの入札価格の最低価格みたいなルールの縛りが無いと、今回の1jpyxみたいに無限に安いレートで入札されてしまい、入札が少なくてそれでauction成立してしまうような状況だと、価格バグって使い物にならないんじゃ？と思ったのですが、何か勘違いしているでしょうか。

auction関連で明示的に確認できる価格はmax_bidとcorresponding debt以外見当たらないので、そのいずれかがその役目を果たすのかなあと思ったりもしたのですが、このあたりにも確信はありません。

まず上記のような複数名からのauctionに対応できる実装になっているか、オークションの実施アカウント(モジュールアカウント≒コントラクトアカウント)から見て最良の価格の入札者が意図通り落札できる結果となっているかといった点に着目して、デバッグしておいたほうが良いと感じています。

上記デバッグ実行の上、結果を把握した上で、フロントエンド・バックエンド双方の実装に確信を得てから次のステップに進みませんか？

確認お願いします。

@KimuraYu45z 
上記疑問にそもそも何らかの勘違いがあったり、上記疑問自体は筋が通っていたとしても、それはさておき、いったんマージしてデプロイしましょうということであれば、この状態でマージする前提で詳細にレビュー着手しようと思います。所感聞かせてくださると助かります。

2021-11-15 06:00 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
以下指摘違和感あれば、フォローくださると助かります。

@Senna46 
本件、改めて、今日少しだけこちらでもデバッグしてみて、以下の点を修正したり、確認したりしてほしいと感じました。

1. place-bidのトランザクションを送る画面に表示されている情報が少なく、入札実行するユーザーが入札内容を把握しにくい。(auctionの詳細画面に表示されている情報は全て表示すべきでは？)
2. place-bidの際にフォームで指定する数量の単位は何なのか？個人的にはこれがフォームから全く読み取れないと感じた。
  1. 1jpyxと指定した場合、何が1jpyxとしてトランザクションが実行されるべきなのか？
    1. 1 debt = 1 jpyxとしてオークションへの入札を行うということか？←これならさほどおかしなレートではない？
    2. 1 ubtc = 1 jpyxとしてオークションへの入札を行うということか？←この場合レート壊れすぎでは？
    3. 全担保 = 1 jpyxとしてオークションへの入札を行うということか？←この場合レート壊れすぎでは？
  2. その仕様通りの動作になっているか？
3. Auctionのparamsの設定通りに落札条件はコントロールできているか？Auctionが発生してから時間がかかりすぎた後の入札となっていて何かイレギュラーな形で落札されていないか？

2021-11-15 06:08 UTC, YasunoriMATSUOKA requested changes
routingをplace-bidとするのであれば、コンポーネントのファイル名やコンポーネントのクラス名はbidやBidでなく、place-bidやPlaceBidとしましょう。(routingと揃える形でお願いします。全ての問題の箇所にコメント入れられているわけではないので、適宜修正しておいてください。)
また、それ以外の点についても、コメント( https://github.com/lcnem/botany/pull/143#issuecomment-968564186 )しているので確認お願いします。

2021-11-15 06:08 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/pages/auction/auctions/auction/bid/bid.component.ts
> +  styleUrls: ['./bid.component.css'],
bidではなく、routingのplace-bidと揃えましょう。

2021-11-15 06:08 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/pages/auction/auctions/auction/bid/bid.component.ts
> +export class BidComponent implements OnInit {
BidComponentではなく、routingのplace-bidと揃えて、PlaceBidComponentとしましょう。

2021-11-15 06:08 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/pages/auction/auctions/auctions-routing.module.ts
> +import { BidComponent } from './auction/bid/bid.component';
bid -> place-bid
BidComponent -> PlaceBidComponent

2021-11-15 06:35 UTC, Senna46 commented
> 1. place-bidのトランザクションを送る画面に表示されている情報が少なく、入札実行するユーザーが入札内容を把握しにくい。(auctionの詳細画面に表示されている情報は全て表示すべきでは？)

オークションサイトの入札画面とかからも、応札するときに同じページから確認する情報はID、商品の情報、現在価格で十分かと思っています。残り時間くらいは追加しても良いかもしれませんが、残り時間指定していないオークションというのがJPYXでは存在するので、残り6078年と表示されるのも微妙なので今回の実装では省いています。


> 2. place-bidの際にフォームで指定する数量の単位は何なのか？個人的にはこれがフォームから全く読み取れないと感じた。

これはこちらからの入札額です。


> 3. 1jpyxと指定した場合、何が1jpyxとしてトランザクションが実行されるべきなのか？
>    1. 1 debt = 1 jpyxとしてオークションへの入札を行うということか？←これならさほどおかしなレートではない？
>    2. 1 ubtc = 1 jpyxとしてオークションへの入札を行うということか？←この場合レート壊れすぎでは？
>    3. 全担保 = 1 jpyxとしてオークションへの入札を行うということか？←この場合レート壊れすぎでは？

JPYXの仕様をみたところ、1個の商品をn個というオークションではなく、n個まとめての出品となっています。
そのため、3の認識で間違いないと思います。
1JPYXで入札が入るのは、0JPYXでなければ入札できるシステムなので問題ないです。参加者が少ないという問題はともかく、1円オークションはシステム上は別にあっても構わないと思うのですがいかがでしょうか。


> 4. その仕様通りの動作になっているか？

MsgPlaceBidは
```
            auction_id?: (Long|null);

            /** MsgPlaceBid bidder */
            bidder?: (string|null);

            /** MsgPlaceBid amount */
            amount?: (cosmos.base.v1beta1.ICoin|null);
```
となっており、システム上も全担保を1商品として入札できていると思われます。その他は残高不足は弾かれるのは確認しています。
Faucetで大量のJPYXを作れなかったのでMaxBidの入札をしたときに落札となるかは確認していません。


> 5. Auctionのparamsの設定通りに落札条件はコントロールできているか？Auctionが発生してから時間がかかりすぎた後の入札となっていて何かイレギュラーな形で落札されていないか？

これは変な挙動となっている可能性があります。先週末1jpyxの入札を入れたID:2が消えています。EndTimeは9000年（指定なし）だったのでそもそも落札されたのか、現在どういう状態か確認しないといけません。

2021-11-15 06:57 UTC, YasunoriMATSUOKA commented
> オークションサイトの入札画面とかからも、応札するときに同じページから確認する情報はID、商品の情報、現在価格で十分かと思っています。残り時間くらいは追加しても良いかもしれませんが、残り時間指定していないオークションというのがJPYXでは存在するので、残り6078年と表示されるのも微妙なので今回の実装では省いています。

現状の入札ページに表示されているのは以下情報のみです。(これだけの情報では、入札者がどれくらいのBIDをつけて入札に参加するのが合理的かこの画面からまったく判断できくないですか？)
![image](https://user-images.githubusercontent.com/55148923/141734218-8c86767f-9789-4575-9ffe-1a054dad6488.png)

自分がオークションの入札者だったら、入札ページではなく詳細ページで表示されている以下全情報を見たいです。
![image](https://user-images.githubusercontent.com/55148923/141734319-540842b3-4726-435f-bebf-9f66e83c108c.png)

コンポーネント使いまわせるよう工夫して実装するもよし、一つくらいなら、同じコードをまるっとコピペでもよし、いずれにせよ、入札ページに少なくともCorresponding DebtとMax Bidの情報はほしいと松岡は考えています。

End Time, Max End Timeも、未入札時点では意味のない数字になるのかもしれませんが、入札入ったら条件が変わって意味がある数字が表示される等の可能性もあると思いますし、全ての情報を表示しておくのが、良いと松岡は考えています。(詳細画面と同じ表示内容に、プラスアルファで、オークション入札に必要なフォームが表示されているという構成が自然なのでは？という意見です。)

> 1JPYXで入札が入るのは、0JPYXでなければ入札できるシステムなので問題ないです。参加者が少ないという問題はともかく、1円オークションはシステム上は別にあっても構わないと思うのですがいかがでしょうか。

> Faucetで大量のJPYXを作れなかったのでMaxBidの入札をしたときに落札となるかは確認していません。

懸念しているのは、特に以下2点です。これはデバッグして結果を明示し、問題が無いことを確認してから次に進みましょう。一つのアカウントでFaucetから取得できるトークンだけでデバッグの残高足りない場合、複数のアカウントでFaucetからトークンを取得してデバッグするか、ノード上で直接cliコマンド叩いて必要な額のトークンを取得してデバッグしてください。この前提が崩れている場合、オークションとは名ばかりの、ただの先着順バーゲンセールとなってしまい、本来CDPとして意図しているインセンティブ構造が完全に破綻した状態になっている可能性があります。

1. より有利な価格の入札を後から実行できる状態になっていたか？
2. 最終的に落札された入札は最も高いレートを提示した入札者になっていたか？

> 先週末1jpyxの入札を入れたID:2が消えています。EndTimeは9000年（指定なし）だったのでそもそも落札されたのか、現在どういう状態か確認しないといけません。

これも確認をお願いします。

2021-11-15 08:00 UTC, YasunoriMATSUOKA requested changes
トランザクション送信結果の成功・失敗判定の実装に問題があり、実際には失敗していても成功と判定される状態になっているように思われます。
確認・修正お願いします。

2021-11-15 09:56 UTC, Senna46 commented
@YasunoriMATSUOKA
Fausetから1JPYXも取得できないので、以下のデバッグができておりません。
1jpyxを取ろうとすると以下のエラーが出ます。
```
error: "cannot send tokens (SDK code 5): failed to execute message; message index: 0: 0jpyx is smaller than 1jpyx: insufficient funds"
```
Telescope側のFaucetが未実装ということであればCLIからやろうと思いますが、なにか間違っていたら教えて下さい。


- [ ] 最高入札より安い入札がブロックされるか

- [ ] より有利な価格の入札を後から実行できる状態か

- [ ] 最終的に落札された入札は最も高いレートを提示した入札者になっていたか？


現状確認したもの

- [x] Max Bidは機能している
2133jpyx > 536jpyx: bid is greater than auction's max bid

- [x] 0bidは不可
0jpyx < 1jpyx: bid is not greater than auction's min new bid amount

- [x] 残高より少ないBidは不可
0jpyx is smaller than 1jpyx: insufficient funds

2021-11-15 09:57 UTC, Senna46 commented on projects/telescope-extension/src/app/models/auctions/auction.application.service.ts
> +      if (res.code !== undefined && res.raw_log !== undefined) {
https://github.com/lcnem/botany/pull/143/commits/b26ecfef7cc7760399d2b4f214e98342e500f831
修正しました。動作も確認しています。

2021-11-15 10:01 UTC, YasunoriMATSUOKA commented
jpyxはfaucetから取得せずとも、cdpをcreateすれば取得可能です。

2021-11-16 06:46 UTC, Senna46 commented
最高入札より安い入札がブロックされるか
`Error has occured: Error: failed to execute message; message index: 0: 5jpyx < 6jpyx: bid is not greater than auction's min new bid amount`

そもそもtx自体が通らないので正しい挙動かと思います。

2021-11-16 07:32 UTC, Senna46 commented
デバッグ結果のまとめ

AuctionはEnd Time未設定の場合、EndTime、MaxEndTimeともに9000年になる。入札がない限り残り続ける。

初入札が起こったとき、Auction発生時間に関係なく
→　End Time　1時間後          Max End Time　2日後
に設定される。

有利な入札（+1jpyx以上、それ以外はTxが通らない）の場合、キーは同じでも異なっていても
→　End Time　最後の入札から1時間後          Max End Time　最初の入札から2日後のまま
に設定される。

有利な入札があった時点で前の入札のJPYXは残高に戻るTxが走る。
しかし、最高入札者は残高の一部がロックされた状態になるため、300JPYホルダーが最高入札者のとき、200JPYXを250JPYXに変えるということは仕組み上不可能

残高に落札が反映されるかは上記の通り、1時間後に確認します。

2021-11-16 07:48 UTC, YasunoriMATSUOKA commented
「キーは同じでも異なっていても」というのはどういう意味でしょうか？

2021-11-16 07:59 UTC, YasunoriMATSUOKA commented
@Senna46 

> 有利な入札があった時点で前の入札のJPYXは残高に戻るTxが走る。
> しかし、最高入札者は残高の一部がロックされた状態になるため、300JPYホルダーが最高入札者のとき、200JPYXを250JPYXに変えるということは仕組み上不可能

上記の2文目ですが、「最高入札者は残高の一部がロックされた状態になっているようで、300jpyxホルダーが200jpyxで最高入札者のとき、他のアカウントからの200jpyxを上回る入札が無いにも関わらず、自分自身だけで現状の最高入札額200jpyxを250jpyxに変えるというトランザクションを投げようとすると、残高不足でトランザクションは通らなかった」という理解であっていますか？

松岡の所感としては、これで問題ないかなと思ったのですが、 @KimuraYu45z 、この挙動で問題ないでしょうか？(誰か別の人が自分よりも高い価格を掲示して入札していないのに、自分自身でより高い価格を開示して再度入札する必要はないと思ったので...)

2021-11-16 08:04 UTC, KimuraYu45z commented
そうですね300あるひとが200の投げたら暫定的に残高は100になるので250のは投げられなくなります。

2021-11-16 08:17 UTC, Senna46 commented
@YasunoriMATSUOKA 
1つ目
同じ人が残高を使ってさらに高い値段でのBidをおこなっても延長ルールが適用されるという認識でOKです。

2つ目
松岡さんの理解であっています。私も特に問題はないと思うのと、JPYXのauctionの仕組み的に実装は厳しいと思っています。

2021-11-16 08:22 UTC, YasunoriMATSUOKA commented
@Senna46 
下記確認以外は全て完了している認識でしょうか？もしそうなら先にコードレビューしておこうかなと思っているのですがいかがでしょう？

> 残高に落札が反映されるかは上記の通り、1時間後に確認します。

2021-11-16 08:31 UTC, Senna46 commented
これについても確認完了しました。残高への反映問題ありません。

＞残高に落札が反映されるかは上記の通り、1時間後に確認します。

before
![test4before](https://user-images.githubusercontent.com/29295263/141949038-7ab8179f-0acc-4daa-90e7-e49f67f059db.PNG)

![test4auc](https://user-images.githubusercontent.com/29295263/141949059-f67ca882-1607-4889-8cd6-8ec2accd7b76.PNG)

after
![test4after](https://user-images.githubusercontent.com/29295263/141949085-37431423-6a57-41c4-9c08-4a8d82f6e8d4.PNG)

2021-11-16 08:31 UTC, YasunoriMATSUOKA commented
@Senna46 
ではすべての修正が完了している認識で、再度こちらでコードレビュー行ってよいでしょうか？

2021-11-16 08:32 UTC, Senna46 commented
@YasunoriMATSUOKA 
デバッグ完了という認識です。よろしくお願いいいたします。

2021-11-16 08:51 UTC, YasunoriMATSUOKA requested changes
@Senna46 
routingのbid -> place-bidへの修正ができれば全て修正完了と思います。
確認と修正お願いします。

2021-11-16 08:51 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/pages/auction/auctions/auctions-routing.module.ts
> +  },
routingは以下リンクのSlackコメントを基点にした議論で、bidではなく、place-bidにしましょうという話にならなかったでしょうか？修正お願いします。
https://cauchye.slack.com/archives/CKV987JSW/p1636956934023700

2021-11-16 08:56 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/pages/auction/auctions/auctions-routing.module.ts
> +  },
ああ、でもそうすると、このページへの遷移ボタンのリンクも修正しないといけないのかな。漏れないよう注意してください。

2021-11-16 08:58 UTC, YasunoriMATSUOKA requested changes

2021-11-16 08:58 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/views/auction/auctions/auction/auction.component.html
> +  >
@Senna46 
ここも、bid -> place-bidに変更する必要あると思います。
ご注意ください。

2021-11-16 13:14 UTC, Senna46 commented
@YasunoriMATSUOKA [
置換した際に漏れていたようです、お手数おかけしました。
変更しましたので、確認お願いします。

2021-11-17 02:26 UTC, YasunoriMATSUOKA approved these changes
LGTM!

2021-11-17 02:27 UTC, YasunoriMATSUOKA commented
こちらでマージしておきます。

2021-11-17 02:27 UTC, merged