feat: config
lcnem/botany pull request #22
Opened 2021-07-03 13:32 UTC by KimuraYu45z

https://github.com/lcnem/botany/issues/21

2021-07-03 13:55 UTC, YasunoriMATSUOKA requested changes
アドバイス＆プルリク作成ありがとうございます。
まだ実際に動作させてデバッグできていないのですが、コメント入れた箇所は違和感があったため、明日、該当箇所を修正して全体的に再度デバッグして、必要な修正等あれば、こちらからも修正コミット入れさせて頂ければと思います。

2021-07-03 13:55 UTC, YasunoriMATSUOKA commented on projects/cosmoscan-extension/editions/eurx/config.js
> +  restURL: `${location.protocol}//${location.hostname}:1317`,
詳細は明日以降こちらでもデバッグ試みようと思っていますが、記録として気になった点に一旦コメント残しておきます。

```ts
誤？: restURL: `${location.protocol}//${location.hostname}:1317`,
正？: restURL: `${location.protocol}://${location.hostname}:1317`,
```

2021-07-03 13:55 UTC, YasunoriMATSUOKA commented on projects/cosmoscan-extension/editions/jpyx/config.js
> +  restURL: `${location.protocol}//${location.hostname}:1317`,
詳細は明日以降こちらでもデバッグ試みようと思っていますが、記録として気になった点に一旦コメント残しておきます。

```ts
誤？: restURL: `${location.protocol}//${location.hostname}:1317`,
正？: restURL: `${location.protocol}://${location.hostname}:1317`,
```

2021-07-03 14:01 UTC, KimuraYu45z commented on projects/cosmoscan-extension/editions/jpyx/config.js
> +  restURL: `${location.protocol}//${location.hostname}:1317`,
http://www.htmq.com/js/location_protocol.shtml
`location.protocol`はコロン付きで返ってくるらしいです！(初見殺しなので仕方ないですｗ)

2021-07-03 14:20 UTC, YasunoriMATSUOKA commented on projects/cosmoscan-extension/editions/jpyx/config.js
> +  restURL: `${location.protocol}//${location.hostname}:1317`,
なんと... ありがとうございます。だとすると、この一行下のwebsocketの方をコロンをとる修正する必要がある感じでしょうか？

2021-07-03 14:34 UTC, KimuraYu45z commented on projects/cosmoscan-extension/editions/jpyx/config.js
> +  restURL: `${location.protocol}//${location.hostname}:1317`,
あ、、、本当だ。。。
ファインプレーありがとうございます🙇

2021-07-05 03:23 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
npm ci がコケているようです...
(ローカルで実行した場合は問題なくnpm ci 実行できましたが、GitHub ActionsのCI環境で問題が発生している状況で、)調べてみたところキャッシュの問題のようで、以下のような情報がヒットしました。
https://qiita.com/holdout0521/items/ebf836fc11e864177628

一時的にGitHub Actionsの処理で上記記事を参考にキャッシュをクリアする手順を試した上で、問題解決後にGitHub Actionsの処理をもとに戻すような形で対処しようと思うのですが、違和感ないでしょうか？

ご確認＆アドバイス頂けると助かります。よろしくお願いします。

2021-07-05 03:24 UTC, KimuraYu45z commented
大丈夫です！的確かと！

2021-07-05 03:26 UTC, YasunoriMATSUOKA commented on projects/cosmoscan-extension/editions/eurx/config.js
> +  restURL: `${location.protocol}//${location.hostname}:1317`,
restURLは上記実装で問題なし。ただし、この一行下のwebsocketURLの実装から:を消す必要があるというのが正確な状況でした。以下で修正済となります。
https://github.com/lcnem/botany/pull/22/commits/865ad37d355f52ed2316662e2963b08f8dcf961e

2021-07-05 03:26 UTC, YasunoriMATSUOKA commented on projects/cosmoscan-extension/editions/jpyx/config.js
> +  restURL: `${location.protocol}//${location.hostname}:1317`,
restURLは上記実装で問題なし。ただし、この一行下のwebsocketURLの実装から:を消す必要があるというのが正確な状況でした。以下で修正済となります。
https://github.com/lcnem/botany/pull/22/commits/865ad37d355f52ed2316662e2963b08f8dcf961e

2021-07-05 03:51 UTC, YasunoriMATSUOKA commented
以下の件、うまくいきました！
https://github.com/lcnem/botany/pull/22#issuecomment-873755676

これでbuildは通ったのでマージします。testは後で対応します。

2021-07-05 03:51 UTC, merged

2021-07-05 04:56 UTC, Senna46 commented
```
Object
key_id: "test1
"__proto__: Object
constructor: ƒ Object()
arguments: (...)
assign: ƒ assign()
caller: (...)
create: ƒ create()
defineProperties: ƒ defineProperties()
defineProperty: ƒ defineProperty()
entries: ƒ entries()freeze: ƒ freeze()
fromEntries: ƒ fromEntries()
getOwnPropertyDescriptor: ƒ getOwnPropertyDescriptor()
getOwnPropertyDescriptors: ƒ getOwnPropertyDescriptors()
getOwnPropertyNames: ƒ getOwnPropertyNames()
getOwnPropertySymbols: ƒ getOwnPropertySymbols()
getPrototypeOf: ƒ getPrototypeOf()
is: ƒ is()
isExtensible: ƒ isExtensible()
isFrozen: ƒ isFrozen()
isSealed: ƒ isSealed()
keys: ƒ keys()
length: 1name: "Object"preventExtensions: ƒ preventExtensions()
prototype: {constructor: ƒ, __defineGetter__: ƒ, __defineSetter__: ƒ, hasOwnProperty: ƒ, __lookupGetter__: ƒ, …}seal: ƒ seal()
setPrototypeOf: ƒ setPrototypeOf()
values: ƒ values()
__proto__: ƒ ()
[[Scopes]]: Scopes[0]hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()toString: ƒ ()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
arguments: (...)
caller: (...)
length: 1name: "set __proto__"__proto__: ƒ ()
[[Scopes]]: Scopes[0]
```
```
main-es2015.0959d046a611d6937889.js:1 
ERROR Error: Uncaught (in promise):
 NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
 NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
Error: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Object.e.create (69-es2015.ec8fc74e1cf6102837b9.js:1)
    at mt (69-es2015.ec8fc74e1cf6102837b9.js:1)
    at 69-es2015.ec8fc74e1cf6102837b9.js:1
    at 69-es2015.ec8fc74e1cf6102837b9.js:1
    at ze (69-es2015.ec8fc74e1cf6102837b9.js:1)
    at He (69-es2015.ec8fc74e1cf6102837b9.js:1)
    at IDBOpenDBRequest.__zone_symbol__ON_PROPERTYsuccess (69-es2015.ec8fc74e1cf6102837b9.js:1)
    at IDBOpenDBRequest.b (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at u.invokeTask (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at Object.onInvokeTask (main-es2015.0959d046a611d6937889.js:1)
    at b (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at polyfills-es2015.989581c8fe9a79eee273.js:1
    at a (main-es2015.0959d046a611d6937889.js:1)
    at u.invoke (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at Object.onInvoke (main-es2015.0959d046a611d6937889.js:1)
    at u.invoke (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at a.run (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at polyfills-es2015.989581c8fe9a79eee273.js:1
    at u.invokeTask (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at Object.onInvokeTask (main-es2015.0959d046a611d6937889.js:1)
mo @ main-es2015.0959d046a611d6937889.js:1
main-es2015.0959d046a611d6937889.js:1 ERROR Error: Uncaught (in promise): NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
 NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
Error: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Object.e.create (69-es2015.ec8fc74e1cf6102837b9.js:1)
    at mt (69-es2015.ec8fc74e1cf6102837b9.js:1)
    at Object.e._trans (69-es2015.ec8fc74e1cf6102837b9.js:1)
    at Object.e.put (69-es2015.ec8fc74e1cf6102837b9.js:1)
    at t.<anonymous> (482-es2015.87168ae20ae93739cd87.js:1)
    at Generator.next (<anonymous>)
    at main-es2015.0959d046a611d6937889.js:1
    at new R (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at o (main-es2015.0959d046a611d6937889.js:1)
    at t.setCurrentKey (482-es2015.87168ae20ae93739cd87.js:1)
    at b (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at polyfills-es2015.989581c8fe9a79eee273.js:1
    at a (main-es2015.0959d046a611d6937889.js:1)
    at u.invoke (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at Object.onInvoke (main-es2015.0959d046a611d6937889.js:1)
    at u.invoke (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at a.run (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at polyfills-es2015.989581c8fe9a79eee273.js:1
    at u.invokeTask (polyfills-es2015.989581c8fe9a79eee273.js:1)
    at Object.onInvokeTask (main-es2015.0959d046a611d6937889.js:1)
mo @ main-es2015.0959d046a611d6937889.js:1
```