feat: receive github action trigger from cosmoscan
lcnem/botany pull request #70
Opened 2021-07-09 08:54 UTC by Senna46

@YasunoriMATSUOKA 
`repository_dispatch`がcosmoscanからtriggerを受け取ったときに、deploy-prodとpricefeed, jpyx, eurxのDocker image作成とpushが動くように変更しています。

2021-07-09 09:35 UTC, YasunoriMATSUOKA requested changes
@Senna46 
Issueを自発的に刈り取っていただきありがとうございます。
修正が必要と思われる点をコメントしておきました。
来週引き続きよろしくお願いします。

2021-07-09 09:35 UTC, YasunoriMATSUOKA commented on .github/workflows/deploy-prod.yml
> +      - repository-cosmoscan-new-release
@Senna46 
こちらのファイルは変更不要です。
deploy-prod.yml で実行されているのは、botanyの中のwebsiteのリソースのみで完結する、firebaseへのデプロイのみなので、こちらについては、cosmoscanのビルド&hubへのプッシュを待って再度デプロイを行う必要はありません。

2021-07-09 09:35 UTC, YasunoriMATSUOKA commented on .github/workflows/docker-botany-pricefeed.yml
> +      - repository-cosmoscan-new-release
@Senna46 
別途会話させてもらいましたが、記録としてコメント残しておきます。
この書き方だと、cosmoscanからイベント通知を受け取った場合も、botanyでリリースした際と同じプロセスが実行されます。イベント通知をトリガーにGitHub Actionsが起動された場合、リリースバージョンという情報が存在しないため、おそらくバージョンをタグに指定したDockerイメージのビルドとDocker Hubへのプッシュは失敗するような気がします。

結論として、イベント通知をトリガーにするGitHub Actionsは、ファイルを分けて、latestタグのみのビルドとプッシュを行う必要があるような気がしています。

他のファイルも同様です。

来週引き続き修正お願いします。

cc: @KimuraYu45z 
もし違和感あればフォローいただけると助かります。

2021-07-09 09:35 UTC, YasunoriMATSUOKA commented on .github/workflows/docker-cosmoscan-eurx.yml
> +      - repository-cosmoscan-new-release
@Senna46 cc: @KimuraYu45z 
docker-botany-pricefeed.yml と同じ指摘となります。

2021-07-09 09:35 UTC, YasunoriMATSUOKA commented on .github/workflows/docker-cosmoscan-jpyx.yml
> +      - repository-cosmoscan-new-release
@Senna46 cc: @KimuraYu45z 
docker-botany-pricefeed.yml と同じ指摘となります。

2021-07-13 08:17 UTC, YasunoriMATSUOKA approved these changes
LGTM

マージして、cosmoscanをリリースして、botany側のGitHub Actionsがうまくトリガーされて動き出すかどうか試してみてください。

2021-07-13 08:17 UTC, YasunoriMATSUOKA commented on .github/workflows/deploy-prod.yml
> +      - repository-cosmoscan-new-release
修正確認済

2021-07-13 08:18 UTC, YasunoriMATSUOKA commented on .github/workflows/docker-botany-pricefeed.yml
> +      - repository-cosmoscan-new-release
修正確認済

2021-07-13 08:18 UTC, YasunoriMATSUOKA commented on .github/workflows/docker-cosmoscan-jpyx.yml
> +      - repository-cosmoscan-new-release
修正確認済

2021-07-13 08:18 UTC, merged

2021-07-13 08:19 UTC, Senna46 commented
ご確認ありがとうございます
木村さんの確認待たず、とりあえずリリースしてみます

2021-07-13 08:24 UTC, YasunoriMATSUOKA commented
@Senna46 
今回の修正での動作検証は、cosmoscan側でリリースをすると、botany側でのdocker関連GitHub Actionsが動作するかどうかを試すということになると思うので、cosmoscanレポジトリの方のリリースを試してみてもらえるとありがたいです。