Feature/botany client
lcnem/botany pull request #88
Opened 2021-09-22 02:25 UTC by KimuraYu45z

botany client、jpyx-3-testに対応

2021-09-22 02:29 UTC, YasunoriMATSUOKA approved these changes
LGTM

2021-09-22 02:29 UTC, YasunoriMATSUOKA commented
とおもったけど、ビルドこけてる？

2021-09-22 02:33 UTC, KimuraYu45z commented
botany clientのほうは修正しました。
telescope extenstionがなぜかこけてますが見たところbotany clientをnpm installしたものをimportせずに相対パスでimportする行儀悪いことやってるからっぽいです。

2021-09-22 02:35 UTC, KimuraYu45z commented
修正中です。

2021-09-22 02:55 UTC, KimuraYu45z commented
もともとこんなCI落ちてましたっけ？ｗ

2021-09-22 02:58 UTC, YasunoriMATSUOKA commented
昨日、faucet途中まで実装した段階では、CI通っていたので、今日このプルリクで加えたbotany-client関連の箇所が影響しているとみるのが自然だとは思いますが(、website側がいきなりCD失敗していたのであれば、何か関連があったりする可能性もあるでしょうか...？)

2021-09-22 03:00 UTC, KimuraYu45z commented
なるほど。faucetがマージされた後で、一気に回収します（とりあえずfaucetに影響でないようにします

2021-09-22 03:02 UTC, YasunoriMATSUOKA commented
ありがとうございますm(__)m
まずは先にFaucetのプルリク進めてFaucetのプルリクマージしてFaucetを含めた形でデプロイし、そのあと、このプルリクで発生している問題を解決して、マージするという流れ、理解しました。
Faucet先に進めていきます。

2021-09-22 13:48 UTC, KimuraYu45z commented
鬼のような破壊的変更量ですが、

https://github.com/lcnem/botany/issues/92
https://github.com/lcnem/botany/issues/89

2021-09-27 02:15 UTC, KimuraYu45z commented
おっとテストをtruthyダミーに変えるのを忘れていました。それやってCI通します。

2021-09-27 02:42 UTC, YasunoriMATSUOKA requested changes
@KimuraYu45z 
トップレベルのappコンポーネントを、

1. pages, viewsディレクトリ配下のappコンポーネントが担うのか、
2. appディレクトリ直下のappコンポーネント + viewsディレクトリ配下のappコンポーネントが担うのか

どちらを意図しているのかちょっとこのプルリクから確信を持てませんでした。
2だと思っているのですが、間違いないでしょうか？

なお、現状だと、`npm run start:telescope:jpyx` してデバッグすると、ng new した直後のAngularの画面が表示されている(appディレクトリ直下のappコンポーネントが表示されていて、そのappコンポーネントはng new 直後の状態になている)ので、修正が必要なのは間違いない状況です。

もし、松岡にて修正したほうが良ければ、その旨、ご指示くださると助かります。
よろしくお願いします。

2021-09-27 02:42 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/app.component.html
> -</view-app>
@KimuraYu45z 
おそらくこの内容を引き継ぐ必要があったのではないかと思うのですが、途中の作業過程で、意図せず、ng new 直後のデフォルトコンテンツに置き換わってしまっていないでしょうか？
違和感を感じたので、確認お願いします。
こちらで修正進めた方が良ければその旨ご指示ください。

2021-09-27 02:42 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/app.module.ts
> -export class AppModule {}
@KimuraYu45z 
こちらもapp.component.htmlへの指摘と同様に、意図せず、ng new 直後の状態になってしまっているような気がします。

2021-09-27 02:42 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/pages/app.component.html
> +</view-app>
@KimuraYu45z 
このファイルはなくし、appディレクトリ直下の、app.component.htmlが、このファイルの役割を果たすよう修正する意図でしょうか？

2021-09-27 02:42 UTC, YasunoriMATSUOKA commented on projects/telescope-extension/src/app/pages/app.component.html
> +</view-app>
いや、逆なのでしょうか？ちょっと判断に迷いました。

2021-09-27 02:43 UTC, KimuraYu45z commented
app.moduleはng newしたときの位置のものをそのまま使うので、pagesの下にあるapp.moduleは削除しました。

2021-09-27 02:59 UTC, KimuraYu45z commented
```bash
npm run start:telescope:jpyx
```

にて、動作確認しました。

2021-09-27 03:03 UTC, KimuraYu45z commented
https://github.com/lcnem/botany/issues/101
本件issue建てて別PRで治す予定です。

2021-09-27 03:03 UTC, KimuraYu45z commented on projects/telescope-extension/src/app/app.component.html
> -</view-app>
おっしゃる通りでした。なぜかpages以下に退避させていました。pages以下のを削除してng newの場所のファイルに内容を移植しました。

2021-09-27 03:19 UTC, YasunoriMATSUOKA approved these changes
@KimuraYu45z 
こちらでも動作確認できたのでapproveします。

なお、現状のconfig.jsと、telescope, botanyの実装では、botany側のみFaucetのリンクが2個表示されてしまう問題が起きる気がするので、以下の別Issueで修正しようと思います。
https://github.com/lcnem/botany/issues/102

2021-09-27 03:20 UTC, merged